use_frameworks!

source 'https://github.com/A-Jun/XiaoYuSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'XiaoYu_Login_Example' do
  pod 'XiaoYu_Login', :path => '../'

  target 'XiaoYu_Login_Tests' do
    inherit! :search_paths

    
  end
end
